# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Pester Tests
        uses: zyborg/pester-tests-report@v1.3.3
        with:
          include_paths: tests
          report_name: tss_tests
          output_level: Minimal
          report_title: Thycotic.SecretServer Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output Test Results
        shell: pwsh
        run: |
          Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
          Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
          Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'